# Generated by Django 5.2.8 on 2025-12-04 01:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[("patient", "患者"), ("doctor", "认证医生"), ("admin", "管理员")],
                default="patient",
                max_length=20,
                verbose_name="用户角色",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="verification_documents",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="verification_docs/",
                verbose_name="认证材料",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="verification_notes",
            field=models.TextField(blank=True, null=True, verbose_name="认证备注"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("unverified", "未认证"),
                    ("pending", "待审核"),
                    ("verified", "已认证"),
                ],
                default="unverified",
                max_length=20,
                verbose_name="认证状态",
            ),
        ),
    ]
