# Generated by Django 5.2.8 on 2025-12-01 22:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="城市名称")),
                (
                    "adcode",
                    models.CharField(max_length=10, unique=True, verbose_name="行政区划代码"),
                ),
                ("patient_count", models.IntegerField(default=0, verbose_name="患者数量")),
                ("clinic_count", models.IntegerField(default=0, verbose_name="诊所数量")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "城市",
                "verbose_name_plural": "城市",
                "ordering": ["-patient_count"],
            },
        ),
        migrations.CreateModel(
            name="Province",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="省份名称"),
                ),
                (
                    "adcode",
                    models.CharField(max_length=10, unique=True, verbose_name="行政区划代码"),
                ),
                ("patient_count", models.IntegerField(default=0, verbose_name="患者数量")),
                ("clinic_count", models.IntegerField(default=0, verbose_name="诊所数量")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "省份",
                "verbose_name_plural": "省份",
                "ordering": ["-patient_count"],
            },
        ),
        migrations.CreateModel(
            name="Clinic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="诊所名称")),
                ("address", models.TextField(blank=True, verbose_name="地址")),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="电话"),
                ),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clinics",
                        to="map.city",
                        verbose_name="所在城市",
                    ),
                ),
            ],
            options={
                "verbose_name": "诊所",
                "verbose_name_plural": "诊所",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Memorial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="姓名")),
                (
                    "birth_date",
                    models.DateField(blank=True, null=True, verbose_name="出生日期"),
                ),
                ("death_date", models.DateField(verbose_name="逝世日期")),
                ("message", models.TextField(blank=True, verbose_name="留言")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="map.city",
                        verbose_name="所在城市",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
            ],
            options={
                "verbose_name": "纪念园",
                "verbose_name_plural": "纪念园",
                "ordering": ["-death_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="patients",
                        to="map.city",
                        verbose_name="所在城市",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="关联用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "患者",
                "verbose_name_plural": "患者",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="city",
            name="province",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cities",
                to="map.province",
                verbose_name="所属省份",
            ),
        ),
        migrations.CreateModel(
            name="HealthLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="日期")),
                (
                    "severity",
                    models.IntegerField(
                        choices=[
                            (1, "等级 1"),
                            (2, "等级 2"),
                            (3, "等级 3"),
                            (4, "等级 4"),
                            (5, "等级 5"),
                            (6, "等级 6"),
                            (7, "等级 7"),
                            (8, "等级 8"),
                            (9, "等级 9"),
                            (10, "等级 10"),
                        ],
                        verbose_name="严重程度 (1-10)",
                    ),
                ),
                ("symptoms", models.JSONField(default=dict, verbose_name="症状")),
                ("medication", models.TextField(blank=True, verbose_name="用药情况")),
                (
                    "sleep_quality",
                    models.IntegerField(
                        choices=[
                            (1, "等级 1"),
                            (2, "等级 2"),
                            (3, "等级 3"),
                            (4, "等级 4"),
                            (5, "等级 5"),
                            (6, "等级 6"),
                            (7, "等级 7"),
                            (8, "等级 8"),
                            (9, "等级 9"),
                            (10, "等级 10"),
                        ],
                        verbose_name="睡眠质量 (1-10)",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="备注")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_logs",
                        to="map.patient",
                        verbose_name="患者",
                    ),
                ),
            ],
            options={
                "verbose_name": "健康日志",
                "verbose_name_plural": "健康日志",
                "ordering": ["-date", "-created_at"],
                "unique_together": {("patient", "date")},
            },
        ),
    ]
